DROP TABLE IF EXISTS `{{article}}`;
DROP TABLE IF EXISTS `{{article_category}}`;
DROP TABLE IF EXISTS `{{article_picture}}`;
DROP TABLE IF EXISTS `{{article_reader}}`;
DROP TABLE IF EXISTS `{{article_approval}}`;
DROP TABLE IF EXISTS `{{article_back}}`;
DELETE FROM `{{setting}}` WHERE `skey` = 'articlemessageenable';
DELETE FROM `{{setting}}` WHERE `skey` = 'articlecommentenable';
DELETE FROM `{{setting}}` WHERE `skey` = 'articlevoteenable';
DELETE FROM `{{setting}}` WHERE `skey` = 'articleapprover';
DELETE FROM `{{setting}}` WHERE `skey` = 'articlethumbenable';
DELETE FROM `{{setting}}` WHERE `skey` = 'articlethumbwh';
DELETE FROM `{{nav}}` WHERE `module` = 'article';
DELETE FROM `{{menu}}` WHERE `m` = 'article';
DELETE FROM `{{notify_node}}` WHERE `module` = 'article';
DELETE FROM `{{notify_message}}` WHERE `module` = 'article';
DELETE FROM `{{credit_rule}}` WHERE `action` = 'addarticle';
DELETE FROM `{{syscache}}` WHERE `name` = 'articlecategory';
DELETE FROM `{{node}}` WHERE `module` = 'article';
DELETE FROM `{{node_related}}` WHERE `module` = 'article';
DELETE FROM `{{auth_item}}` WHERE `name` LIKE 'article%';
DELETE FROM `{{auth_item_child}}` WHERE `child` LIKE 'article%';
DELETE FROM `{{menu_common}}` WHERE `module` = 'article';