DROP TABLE IF EXISTS `{{doc}}`;
DROP TABLE IF EXISTS `{{doc_category}}`;
DROP TABLE IF EXISTS `{{doc_reader}}`;
DROP TABLE IF EXISTS `{{doc_version}}`;
DROP TABLE IF EXISTS `{{doc_approval}}`;
DROP TABLE IF EXISTS `{{doc_back}}`;
DROP TABLE IF EXISTS `{{rc_type}}`;
DELETE FROM `{{setting}}` WHERE `skey` = 'docconfig';
DELETE FROM `{{nav}}` WHERE `module` = 'officialdoc';
DELETE FROM `{{menu}}` WHERE `m` = 'officialdoc';
DELETE FROM `{{syscache}}` WHERE `name` = 'officialdoccategory';
DELETE FROM `{{notify_node}}` WHERE `module` = 'officialdoc';
DELETE FROM `{{notify_message}}` WHERE `module` = 'officialdoc';
DELETE FROM `{{credit_rule}}` WHERE `action` = 'addofficialdoc';
DELETE FROM `{{node}}` WHERE `module` = 'officialdoc';
DELETE FROM `{{node_related}}` WHERE `module` = 'officialdoc';
DELETE FROM `{{auth_item}}` WHERE `name` LIKE 'officialdoc%';
DELETE FROM `{{auth_item_child}}` WHERE `child` LIKE 'officialdoc%';
DELETE FROM `{{menu_common}}` WHERE `module` = 'officialdoc';
